# -*- coding: utf-8 -*-
# Release notes for version 1.2.2 (a2c9a87a-abe0-47aa-b533-0550d2eae712), the 16 store locales.
# Push with `python3 aso/push_whatsnew.py --write`, verify with `python3 aso/verify.py`.
W = {
"en-US":"Try Earnit before you pay: set it up, go for a walk, and your first unlock is on us. You can also earn time once with push-ups, no subscription needed.\n\nGetting through the Screen Time permission is easier, the camera now tells you what to fix when it can't see you, and the trial terms are clearer before you subscribe. This update also includes bug fixes and reliability improvements.",
"en-GB":"Try Earnit before you pay: set it up, go for a walk, and your first unlock is on us. You can also earn time once with press-ups, no subscription needed.\n\nGetting through the Screen Time permission is easier, the camera now tells you what to fix when it can't see you, and the trial terms are clearer before you subscribe. This update also includes bug fixes and reliability improvements.",
"es-ES":"Prueba Earnit antes de pagar: configúralo, sal a caminar y tu primer desbloqueo corre de nuestra cuenta. También puedes ganar tiempo una vez con flexiones, sin suscripción.\n\nAhora es más fácil completar el permiso de Tiempo de uso, la cámara te indica qué ajustar cuando no te ve y las condiciones de la prueba son más claras antes de suscribirte. Esta versión incluye además correcciones y mejoras de fiabilidad.",
"es-MX":"Prueba Earnit antes de pagar: configúralo, sal a caminar y tu primer desbloqueo va por nuestra cuenta. También puedes ganar tiempo una vez con lagartijas, sin suscripción.\n\nAhora es más fácil completar el permiso de Tiempo en pantalla, la cámara te indica qué ajustar cuando no te ve y las condiciones de la prueba son más claras antes de suscribirte. Esta versión incluye además correcciones y mejoras de confiabilidad.",
"de-DE":"Teste Earnit, bevor du zahlst: Richte es ein, geh spazieren – deine erste Freischaltung geht auf uns. Einmal kannst du dir Zeit auch mit Liegestützen verdienen, ganz ohne Abo.\n\nDie Bildschirmzeit-Berechtigung ist jetzt einfacher einzurichten, die Kamera sagt dir, was du ändern musst, wenn sie dich nicht erkennt, und die Testbedingungen sind vor dem Abschluss klarer. Außerdem enthält dieses Update Fehlerbehebungen und Verbesserungen der Zuverlässigkeit.",
"fr-FR":"Essayez Earnit avant de payer : configurez-le, allez marcher, et votre premier déblocage est offert. Vous pouvez aussi gagner du temps une fois avec des pompes, sans abonnement.\n\nL'autorisation Temps d'écran est plus simple à accorder, la caméra vous dit quoi corriger quand elle ne vous voit pas, et les conditions de l'essai sont plus claires avant de vous abonner. Cette version apporte aussi des corrections et des améliorations de fiabilité.",
"it":"Prova Earnit prima di pagare: configuralo, fai una passeggiata e il primo sblocco lo offriamo noi. Puoi anche guadagnare tempo una volta con le flessioni, senza abbonamento.\n\nConcedere il permesso di Tempo di utilizzo è più semplice, la fotocamera ti dice cosa sistemare quando non ti vede e le condizioni della prova sono più chiare prima di abbonarti. Questo aggiornamento include anche correzioni e miglioramenti di affidabilità.",
"pt-BR":"Experimente o Earnit antes de pagar: configure, saia para caminhar e seu primeiro desbloqueio é por nossa conta. Você também pode ganhar tempo uma vez com flexões, sem assinatura.\n\nFicou mais fácil concluir a permissão do Tempo de Uso, a câmera indica o que ajustar quando não consegue te ver e as condições do teste estão mais claras antes de assinar. Esta versão também traz correções e melhorias de confiabilidade.",
"nl-NL":"Probeer Earnit voordat je betaalt: stel het in, ga wandelen en je eerste ontgrendeling is van ons. Je kunt ook één keer tijd verdienen met push-ups, zonder abonnement.\n\nDe schermtijdtoestemming is makkelijker te geven, de camera vertelt wat je moet aanpassen als hij je niet ziet en de proefvoorwaarden zijn duidelijker voordat je een abonnement neemt. Deze update bevat ook bugfixes en verbeteringen in betrouwbaarheid.",
"pl":"Wypróbuj Earnit, zanim zapłacisz: skonfiguruj aplikację, idź na spacer, a pierwsze odblokowanie masz od nas. Raz możesz też zdobyć czas pompkami, bez subskrypcji.\n\nUdzielenie uprawnienia Czas przed ekranem jest prostsze, kamera podpowiada, co poprawić, gdy cię nie widzi, a warunki okresu próbnego są jaśniejsze przed zakupem subskrypcji. Aktualizacja zawiera też poprawki błędów i większą niezawodność.",
"tr":"Earnit'i ödeme yapmadan önce dene: kur, yürüyüşe çık, ilk kilit açma bizden. Abonelik olmadan bir kez de şınavla süre kazanabilirsin.\n\nEkran Süresi iznini vermek artık daha kolay, kamera seni göremediğinde neyi düzeltmen gerektiğini söylüyor ve deneme koşulları abone olmadan önce daha net. Bu sürüm ayrıca hata düzeltmeleri ve güvenilirlik iyileştirmeleri içeriyor.",
"ru":"Попробуйте Earnit до оплаты: настройте приложение, прогуляйтесь — и первая разблокировка за наш счёт. Один раз можно заработать время и отжиманиями, без подписки.\n\nРазрешение «Экранное время» теперь проще выдать, камера подсказывает, что исправить, если не видит вас, а условия пробного периода стали понятнее до оформления подписки. Также в обновлении исправлены ошибки и повышена надёжность.",
"ja":"お支払いの前にEarnitをお試しください。設定して散歩に出かければ、最初のロック解除は無料です。サブスクリプションなしで、腕立て伏せで一度だけ時間を獲得することもできます。\n\nスクリーンタイムの許可がよりスムーズになり、カメラに映らないときは直すべき点を案内するようになりました。登録前のトライアル条件も分かりやすくなっています。バグ修正と信頼性の向上も含まれます。",
"ko":"결제 전에 Earnit을 사용해 보세요. 설정하고 산책을 다녀오면 첫 잠금 해제는 무료입니다. 구독 없이 팔굽혀펴기로 한 번 시간을 얻을 수도 있습니다.\n\n스크린 타임 권한 허용이 더 쉬워졌고, 카메라가 사용자를 인식하지 못할 때 무엇을 조정해야 하는지 알려 줍니다. 구독 전 체험 조건도 더 명확해졌습니다. 버그 수정과 안정성 개선도 포함되어 있습니다.",
"zh-Hans":"付费前先试用 Earnit：完成设置，出门走一走，第一次解锁由我们买单。无需订阅，你还可以用俯卧撑获得一次时间。\n\n屏幕使用时间权限的授权流程更简单；摄像头看不到你时会提示需要调整的地方；订阅前的试用条款也更加清晰。本次更新还包含问题修复和稳定性改进。",
"ar-SA":"جرّب Earnit قبل أن تدفع: أعدّه، واخرج للمشي، وأول فتح للتطبيقات علينا. يمكنك أيضاً كسب الوقت مرة واحدة بتمارين الضغط دون اشتراك.\n\nأصبح منح إذن مدة استخدام الجهاز أسهل، وتخبرك الكاميرا بما يجب تعديله عندما لا تراك، وأصبحت شروط الفترة التجريبية أوضح قبل الاشتراك. يتضمن هذا الإصدار أيضاً إصلاحات للأخطاء وتحسينات في الموثوقية.",
}
