# -*- coding: utf-8 -*-
# Release notes for version 1.3.0 (4dafd77d-77aa-4bb9-9187-979c7f6e420e), the 16 store locales.
# Push with `python3 aso/push_whatsnew.py --write`, verify with `python3 aso/verify.py`.
W = {
"en-US":"New: earn screen time with squats. Choose squats or push-ups, prop your phone up, and the camera counts every rep live on your iPhone. Squats need no floor space, so you can earn a few minutes wherever you are.\n\nEarnit can now also send you a gentle reminder when you haven't earned in a while. This update also includes bug fixes and reliability improvements.",
"en-GB":"New: earn screen time with squats. Choose squats or press-ups, prop your phone up, and the camera counts every rep live on your iPhone. Squats need no floor space, so you can earn a few minutes wherever you are.\n\nEarnit can now also send you a gentle reminder when you haven't earned in a while. This update also includes bug fixes and reliability improvements.",
"es-ES":"Novedad: gana tiempo de pantalla con sentadillas. Elige sentadillas o flexiones, apoya el móvil y la cámara cuenta cada repetición en directo en tu iPhone. Las sentadillas no necesitan suelo libre, así que puedes ganar unos minutos estés donde estés.\n\nAdemás, Earnit puede enviarte un recordatorio amable cuando lleves tiempo sin ganar minutos. Esta versión incluye también correcciones y mejoras de fiabilidad.",
"es-MX":"Novedad: gana tiempo en pantalla con sentadillas. Elige sentadillas o lagartijas, apoya tu celular y la cámara cuenta cada repetición en vivo en tu iPhone. Las sentadillas no necesitan espacio en el piso, así que puedes ganar unos minutos estés donde estés.\n\nAdemás, Earnit puede enviarte un recordatorio amable cuando lleves tiempo sin ganar minutos. Esta versión incluye también correcciones y mejoras de confiabilidad.",
"de-DE":"Neu: Verdiene Bildschirmzeit mit Kniebeugen. Wähle Kniebeugen oder Liegestütze, stell dein Handy auf, und die Kamera zählt jede Wiederholung live auf deinem iPhone. Für Kniebeugen brauchst du keinen Platz auf dem Boden – so verdienst du dir überall ein paar Minuten.\n\nAußerdem kann Earnit dich jetzt sanft erinnern, wenn du länger nichts verdient hast. Dieses Update enthält außerdem Fehlerbehebungen und Verbesserungen der Zuverlässigkeit.",
"fr-FR":"Nouveau : gagnez du temps d’écran avec des squats. Choisissez squats ou pompes, posez votre téléphone et la caméra compte chaque répétition en direct sur votre iPhone. Les squats ne demandent pas de place au sol : vous pouvez gagner quelques minutes où que vous soyez.\n\nEarnit peut aussi vous envoyer un petit rappel quand vous n’avez rien gagné depuis un moment. Cette mise à jour comprend également des corrections de bugs et des améliorations de fiabilité.",
"it":"Novità: guadagna tempo schermo con gli squat. Scegli squat o flessioni, appoggia il telefono e la fotocamera conta ogni ripetizione dal vivo sul tuo iPhone. Per gli squat non serve spazio a terra, così puoi guadagnare qualche minuto ovunque tu sia.\n\nEarnit ora può anche mandarti un promemoria gentile quando non guadagni da un po’. Questo aggiornamento include anche correzioni di bug e miglioramenti dell’affidabilità.",
"pt-BR":"Novidade: ganhe tempo de tela com agachamentos. Escolha agachamentos ou flexões, apoie o celular e a câmera conta cada repetição ao vivo no seu iPhone. Agachamentos não precisam de espaço no chão, então você ganha alguns minutos onde estiver.\n\nO Earnit agora também pode enviar um lembrete gentil quando você ficar um tempo sem ganhar. Esta atualização também traz correções de bugs e melhorias de confiabilidade.",
"nl-NL":"Nieuw: verdien schermtijd met squats. Kies squats of push-ups, zet je telefoon neer en de camera telt elke herhaling live op je iPhone. Voor squats heb je geen vloerruimte nodig, dus je verdient overal een paar minuten.\n\nEarnit kan je nu ook een vriendelijke herinnering sturen als je een tijdje niets hebt verdiend. Deze update bevat ook bugfixes en verbeteringen in de betrouwbaarheid.",
"pl":"Nowość: zdobywaj czas przed ekranem przysiadami. Wybierz przysiady lub pompki, postaw telefon, a kamera policzy każde powtórzenie na żywo na Twoim iPhonie. Przysiady nie wymagają miejsca na podłodze, więc kilka minut zdobędziesz wszędzie.\n\nEarnit może teraz także wysłać Ci delikatne przypomnienie, gdy od dawna nic nie zdobyłeś. Ta aktualizacja zawiera również poprawki błędów i usprawnienia niezawodności.",
"tr":"Yeni: Squat yaparak ekran süresi kazan. Squat veya şınavı seç, telefonunu yasla; kamera her tekrarı iPhone’unda canlı olarak sayar. Squat için yerde boş alana gerek yok, böylece nerede olursan ol birkaç dakika kazanabilirsin.\n\nEarnit artık bir süredir kazanmadığında sana nazik bir hatırlatma da gönderebiliyor. Bu güncelleme ayrıca hata düzeltmeleri ve güvenilirlik iyileştirmeleri içerir.",
"ru":"Новое: зарабатывайте экранное время приседаниями. Выберите приседания или отжимания, поставьте телефон — и камера считает каждое повторение в реальном времени прямо на iPhone. Для приседаний не нужно место на полу, так что пару минут можно заработать где угодно.\n\nТеперь Earnit также может мягко напомнить о себе, если вы давно ничего не зарабатывали. Обновление также содержит исправления ошибок и улучшения стабильности.",
"ja":"新機能：スクワットでスクリーンタイムを獲得。スクワットか腕立て伏せを選んでスマホを立てかければ、iPhone上のカメラが回数をリアルタイムでカウントします。スクワットなら床のスペースは不要なので、どこでも数分を獲得できます。\n\nしばらく獲得していないときは、Earnitがやさしくリマインドするようになりました。そのほか、不具合の修正と安定性の向上を行いました。",
"ko":"새 기능: 스쿼트로 스크린 타임을 얻으세요. 스쿼트나 팔굽혀펴기를 고르고 휴대폰을 세워 두면 iPhone에서 카메라가 모든 반복을 실시간으로 셉니다. 스쿼트는 바닥 공간이 필요 없어 어디서든 몇 분을 벌 수 있어요.\n\n한동안 시간을 얻지 않으면 Earnit이 부드럽게 알려 드릴 수도 있습니다. 이번 업데이트에는 버그 수정과 안정성 개선도 포함되어 있습니다.",
"zh-Hans":"新功能：用深蹲赚取屏幕时间。选择深蹲或俯卧撑，把手机立好，摄像头就会在你的 iPhone 上实时计数每一次动作。深蹲不需要地面空间，随时随地都能赚几分钟。\n\n如果你有一段时间没有赚取时间，Earnit 现在还会温和地提醒你。本次更新还包含问题修复和稳定性改进。",
"ar-SA":"جديد: اكسب وقت الشاشة بتمارين القرفصاء. اختر القرفصاء أو تمارين الضغط، وثبّت هاتفك، وستعدّ الكاميرا كل تكرار مباشرةً على جهاز iPhone. لا تحتاج القرفصاء إلى مساحة على الأرض، لذا يمكنك كسب بضع دقائق أينما كنت.\n\nيمكن لـ Earnit الآن أيضاً أن يرسل لك تذكيراً لطيفاً إذا لم تكسب وقتاً منذ فترة. يتضمن هذا التحديث أيضاً إصلاحات للأخطاء وتحسينات في الموثوقية.",
}
