# -*- coding: utf-8 -*-
W = {
"en-US":"Two new ways to earn your minutes: focused study sessions, and push-ups counted right on your iPhone. Walking still works exactly as before.\n\nAlso: a redesigned home that shows only today, and a Progress tab with your 30-day journey and monthly totals.",
"en-GB":"Two new ways to earn your minutes: focused study sessions, and press-ups counted right on your iPhone. Walking still works exactly as before.\n\nAlso: a redesigned home that shows only today, and a Progress tab with your 30-day journey and monthly totals.",
"es-ES":"Dos formas nuevas de ganar minutos: sesiones de estudio concentradas y flexiones contadas en el propio iPhone. Caminar sigue funcionando igual que antes.\n\nAdemás: un inicio rediseñado que solo muestra hoy, y una pestaña de Progreso con tu recorrido de 30 días y los totales del mes.",
"es-MX":"Dos formas nuevas de ganar minutos: sesiones de estudio concentradas y lagartijas contadas en el propio iPhone. Caminar sigue funcionando igual que antes.\n\nAdemás: un inicio rediseñado que solo muestra hoy, y una pestaña de Progreso con tu recorrido de 30 días y los totales del mes.",
"de-DE":"Zwei neue Wege, Minuten zu verdienen: konzentrierte Lernsessions und Liegestütze, die dein iPhone selbst zählt. Laufen funktioniert genau wie bisher.\n\nAußerdem: ein neu gestalteter Start, der nur den heutigen Tag zeigt, und ein Fortschritt-Tab mit deiner 30-Tage-Reise und den Monatssummen.",
"fr-FR":"Deux nouvelles façons de gagner des minutes : des sessions de révision concentrées et des pompes comptées directement par votre iPhone. La marche fonctionne exactement comme avant.\n\nAussi : un accueil repensé qui n'affiche que la journée en cours, et un onglet Progression avec votre parcours de 30 jours et les totaux mensuels.",
"it":"Due nuovi modi di guadagnare minuti: sessioni di studio concentrate e flessioni contate direttamente dall'iPhone. Camminare funziona esattamente come prima.\n\nInoltre: una home ridisegnata che mostra solo oggi, e una scheda Progressi con il percorso di 30 giorni e i totali mensili.",
"pt-BR":"Duas novas formas de ganhar minutos: sessões de estudo concentradas e flexões contadas pelo próprio iPhone. Caminhar continua funcionando exatamente como antes.\n\nTambém: uma tela inicial redesenhada que mostra só o hoje, e uma aba de Progresso com sua jornada de 30 dias e os totais do mês.",
"nl-NL":"Twee nieuwe manieren om minuten te verdienen: geconcentreerde studiesessies en push-ups die je iPhone zelf telt. Wandelen werkt precies zoals eerst.\n\nVerder: een opnieuw ontworpen start die alleen vandaag laat zien, en een tabblad Voortgang met je reis van 30 dagen en maandtotalen.",
"pl":"Dwa nowe sposoby zdobywania minut: skupione sesje nauki i pompki liczone bezpośrednio przez iPhone'a. Chodzenie działa dokładnie tak jak wcześniej.\n\nPoza tym: przeprojektowany ekran główny pokazujący tylko dzisiaj oraz zakładka Postęp z trzydziestodniową drogą i sumami miesięcznymi.",
"tr":"Dakika kazanmanın iki yeni yolu: odaklanmış çalışma seansları ve doğrudan iPhone'unun saydığı şınavlar. Yürüyüş tam olarak eskisi gibi çalışıyor.\n\nAyrıca: yalnızca bugünü gösteren yeniden tasarlanmış bir ana ekran ve 30 günlük yolculuğunla aylık toplamların bulunduğu bir İlerleme sekmesi.",
"ru":"Два новых способа заработать минуты: сосредоточенные учебные сессии и отжимания, которые считает сам iPhone. Ходьба работает ровно так же, как раньше.\n\nКроме того: обновлённый экран «Сегодня», показывающий только текущий день, и вкладка «Прогресс» с путём на 30 дней и месячными итогами.",
"ja":"分を稼ぐ方法が2つ増えました。集中した勉強セッションと、iPhoneが自分で数える腕立て伏せです。歩数はこれまでどおり使えます。\n\nさらに、今日だけを映す新しいホームと、30日の道のりと月間合計をまとめた「進捗」タブを追加しました。",
"ko":"시간을 버는 방법이 두 가지 늘었습니다. 집중한 공부 세션과, iPhone이 직접 세는 팔굽혀펴기입니다. 걷기는 이전과 똑같이 작동합니다.\n\n또한 오늘만 보여주는 새 홈 화면과, 30일의 여정과 월간 합계를 담은 '진행' 탭이 추가되었습니다.",
"zh-Hans":"新增两种赚取分钟的方式：专注的学习会话，以及由 iPhone 自己计数的俯卧撑。走路的用法和以前完全一样。\n\n此外：重新设计的主页只显示今天，新增「进度」标签页，包含 30 天旅程与月度合计。",
"ar-SA":"طريقتان جديدتان لكسب دقائقك: جلسات دراسة مركّزة، وتمارين ضغط يحسبها جهاز iPhone نفسه. المشي يعمل تماماً كما كان.\n\nكذلك: شاشة رئيسية جديدة تعرض اليوم فقط، وتبويب «التقدم» الذي يضم رحلة الثلاثين يوماً والمجاميع الشهرية.",
}
